export const es = {
    address: 'Dirección',
    cc: 'C.C.',
    ce: 'C.E.',
    city: 'Ciudad',
    code: 'Código',
    colombia: 'República de Colombia',
    consecutiveNumber: 'Número consecutivo',
    daneCode: 'Código DANE',
    day: 'Día',
    department: 'Departamento',
    email: 'E-Mail',
    employingEntity: 'Entidad empleadora',
    fax: 'Fax',
    from: 'Desde',
    identityDocument: 'Documento de identidad',
    month: 'Mes',
    name: 'Nombre',
    nit: 'NIT',
    nitOrCode: 'NIT o código',
    no: 'No',
    number: 'No.',
    of: 'De',
    page: 'Hoja',
    projected: 'Proyectó',
    phone: 'Teléfono',
    sector: 'Sector',
    socialReason: 'Razón social',
    ti: 'T.I.',
    to: 'Hasta',
    warning: 'Advertencia',
    year: 'Año',
    yes: 'Sí',
};
