export const es = {
    address: 'Dirección',
    approved: 'Aprobó',
    box: "Caja",
    cc: 'C.C.',
    ce: 'C.E.',
    city: 'Ciudad',
    code: 'Código',
    colombia: 'República de Colombia',
    consecutiveNumber: 'Número consecutivo',
    daneCode: 'Código DANE',
    date: 'Fecha',
    day: 'Día',
    department: 'Departamento',
    document: 'Documento',
    email: 'E-Mail',
    employingEntity: 'Entidad empleadora',
    end: "Final",
    fax: 'Fax',
    folder: "Carpeta",
    from: 'Desde',
    identification: 'Identificación',
    identityDocument: 'Documento de identidad',
    location: 'Lugar',
    month: 'Mes',
    name: 'Nombre',
    nit: 'NIT',
    nitOrCode: 'NIT o código',
    no: 'No',
    note: "Nota",
    number: 'No.',
    object: "Objeto",
    observations: 'Observaciones',
    of: 'De',
    other: "Otro",
    page: 'Hoja',
    phone: 'Teléfono',
    position: 'Cargo',
    projected: 'Proyectó',
    retention: "Retención",
    responsible: "Responsable",
    sector: 'Sector',
    signature: 'Firma',
    socialReason: 'Razón social',
    start: "Inicial",
    support: "Soporte",
    ti: 'T.I.',
    to: 'Hasta',
    version: 'Versión',
    volume: "Tomo",
    warning: 'Advertencia',
    year: 'Año',
    yes: 'Sí',
};
