export const Strings = {
    title: "Archivo general de la Nación",
    subtitle: "Formato de tabla de retención documental",
    producingEntity: "Entidad productora",
    producingOffice: "Oficina productora",
    seriesAndTypes: "Series y tipos documentales",
    managementFile: "Archivo de gestión",
    centralFile: "Archivo de central",
    finalDisposition: "Disposición final",
    ct: "CT",
    e: "E",
    m: "M",
    s: "S",
    procedures: "Procedimientos",
    conventions: "Convenciones",
    ctExplanation: "CT: Conservación total",
    eExplanation: "E: Eliminación",
    mExplanation: "M: Microfirmación",
    sExplanation: "S: Selección",
    responsibleSignature: "Firma responsable",
}
