export const Strings = {
    version: 2,
    code: "AD-P04-F02",
    sendingEntity: "Entidad remitente",
    conservationUnit: "Unidad de conservación",
    notes: "Notas",
    producingEntity: "Entidad productora",
    administrativeUnit: "Unidad administrativa",
    productionOffice: "Oficina productora",
    invoiceNumber: "Número de folios",
    entranceRegistry: "Registro de entrada",
    frecuency: "Frecuencia de consulta",
    document: "No. Cédula, No. Contrato y/o convenio",
    names: "Nombres",
    series: "Serie, subserie o asunto",
    title: "FORMATO ÚNICO DE INVENTARIO DOCUMENTAL",
    nt: "N°T",
    ntExplanation: "N°T: Número de transferencia.",
    madeBy: "Realizado por",
    deliveredBy: "Entregado por",
    receivedBy: "Recibido por",
    note: "Nota: el diligenciamiento columna 4 aplica para las direcciones de Talento Humano y Contratación. Para los demás procesos no aplica (N.A.).",
}
